### ISSUE TITLE
Correção na sessão "Execução" da documentação

### ISSUE THREAD

**Issue by FelipeFranke5** [unb-mds/2023-2-SuaGradeUnB#190]
### Correção na sessão "Execução" da documentação

**Descreva o erro**
Ao copiar os comandos relacionados ao Docker conforme documentados para o terminal, um erro de "_docker: 'compose' is not a docker command._" é apresentado, se trata de um pequeno erro na digitação do comando.

**Correção**
Corrigir os comandos para:

```
# Se você quiser rodar em segundo plano
docker-compose up -d

# Se alterações foram feitas no Dockerfile ou no docker-compose.yml
docker-compose up --build

# Se for necessário deletar os volumes
docker-compose down -v
```

**Especificações**
![image](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/143849276/8798ae54-bfc6-4c0b-8287-a66c79facdf4)

**Comment by mateusvrs** [comment]
Bom dia Felipe, analisamos sua observação e verificamos que possa ser uma inconsistência na versão do Docker e do Docker Compose que você está utilizando. Poderia, por favor, verificar qual versão está utilizando em sua máquina e reportar aqui?

Isso, visto que nosso projeto utiliza as versões Docker (v24.0.6) e Docker Compose (v2.21.0) e de acordo com a documentação de mudanção do [Compose v1 para o Compose v2](https://docs.docker.com/compose/migrate/), vimos que o comando `docker-compose` seria mais adequado para a versão v1 e o comando `docker compose` para a versão utilizada em nosso projeto que é a v2.

Link de observação: [docker-compose vs docker compose](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose)

**Comment by FelipeFranke5** [comment]
Bom dia @mateusvrs. Interessante, dei uma olhada na versão pelo terminal e me retornou:

Docker: Docker version 24.0.5
Compose: Docker Compose version v2.12.2

**Comment by mateusvrs** [comment]
Outra coisa, mesmo com a utilização do `docker-compose` você conseguiu rodar a aplicação sem mais problemas?

**Comment by FelipeFranke5** [comment]
Vou verificar se o Plugin está instalado e retorno em breve. Talvez de fato não esteja, não sei se interfere, mas estou usando uma versão do Linux Mint no momento.

Com a utilização do `docker-compose` consegui sim.

**Comment by mateusvrs** [comment]
Acredito que a distro linux não deve interferir, mas assim que retornar analisamos e então as alterações que você reportou na documentação possivelmente poderam ser feitas com alguns possíveis ajustes que devo indicar.
Agradeçemos desde já :smiley:

**Comment by FelipeFranke5** [comment]
Executei os comandos para então inicializar novamente o projeto:

```
# Crie um ambiente virtual Python
python3 -m venv api/env

# Ative o ambiente virtual
source api/env/bin/activate

# Instale os pacotes do Python e Node
make install
```

Nesse caso, como ainda não fiz a inclusão do meu usuário no grupo `docker`, posso usar o `sudo docker compose up`, porém ao executar o comando, retornou essa mensagem (Que não me lembro de ter aparecido nos testes anteriores):

_Failed to load /media/felipe/HDD/Pasta sem título/2023-2-SuaGradeUnB/api/.env: open /media/felipe/HDD/Pasta sem título/2023-2-SuaGradeUnB/api/.env: no such file or directory_
![image](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/143849276/bd9d27d3-df77-4673-89ab-abc98f4e7c21)

O mesmo erro aconteceu para `docker compose up`.

Aparentemente algum trecho de código está procurando por api/.env e tenho a pasta api/env quando instalei as dependências do projeto:
![image](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/143849276/52da798b-589b-48a9-8028-16d249fe46f3)

É estranho, porque o erro não tinha acontecido ao usar o `docker-compose` (Na versão antiga), vou tentar reinstalar as dependências para ver se o erro permanece

**Comment by GabrielCastelo-31** [comment]
Olá, @FelipeFranke5! Você conseguiu rodar o projeto?
