### ISSUE TITLE
fix (code scanning alert): Exposição de informações por meio de uma exceção

### ISSUE THREAD

**Issue by GabrielCastelo-31** [unb-mds/2023-2-SuaGradeUnB#201]
## Descrição
Ao lançar uma exceção, o sistema pode expor informações confidenciais, como a pilha de execução da aplicação, que pode revelar dados sensíveis sobre o funcionamento do sistema. 
Por mais útil que seja rastrear a pilha de execução durante o desenvolvimento da aplicação, para corrigir com erros ou realizar debugs, os _logs_ devem ser armazenados de maneira segura e não devem ser acessíveis através do produto final.

### Riscos
Essas informações podem facilitar ataques de hackers, pois a ordem dos nomes das classes em um rastreamento de pilha pode expor a arquitetura da aplicação e os componentes internos que ela utiliza.
Além disso, a mensagem de erro no início de um rastreamento de pilha pode conter informações como nomes de arquivos no servidor e código SQL que a aplicação executa, facilitando um ataque de injeção posterior.

## Solução
Envie ao usuário uma mensagem de erro mais genérica que revele menos informações. Suprima completamente o rastreamento de pilha ou o registre apenas no servidor.

Inspecionado em:
- [ ] https://github.com/unb-mds/2023-2-SuaGradeUnB/security/code-scanning/1983

**Comment by caio-felipee** [comment]
Boa tarde, @GabrielCastelo-31!

Em relação a este problema, eu acredito que já foi solucionado através do pull request #181 e, agora apenas mostramos descrições do tipo `Value Error`. Podemos discutir se esta seria a melhor forma para tratar o erro, mas no momento eu não consigo pensar em um caso que o usuário pode forçar uma exceção deste mesmo tipo sem estar dentro do nosso escopo de tratamento.

Isto acontece pois ao usar o gerador de grades horárias, podemos receber valores que não são válidos como parâmetro. Para uma mensagem de erro mais descritiva, a solução encontrada foi o levantamento de um *Value Error*. Adicionalmente, também acho válido mencionar que mesmo mostrando um erro deste tipo, o que aparece é apenas a descrição do acontecimento.

**Comment by GabrielCastelo-31** [comment]
> Boa tarde, @GabrielCastelo-31!
> 
> Em relação a este problema, eu acredito que já foi solucionado através do pull request #181 e, agora apenas mostramos descrições do tipo `Value Error`. Podemos discutir se esta seria a melhor forma para tratar o erro, mas no momento eu não consigo pensar em um caso que o usuário pode forçar uma exceção deste mesmo tipo sem estar dentro do nosso escopo de tratamento.
> 
> Isto acontece pois ao usar o gerador de grades horárias, podemos receber valores que não são válidos como parâmetro. Para uma mensagem de erro mais descritiva, a solução encontrada foi o levantamento de um _Value Error_. Adicionalmente, também acho válido mencionar que mesmo mostrando um erro deste tipo, o que aparece é apenas a descrição do acontecimento.

Compreendido, Caio! Realmente a exceção foi tratada corretamente e de maneira segura. Darei _dismiss_ nesse alerta de segurança e fecharei a issue. Obrigado pela observação!
